---
title: "CS2007: Machine Learning Techniques"
---

:::{.callout-note}
This site is still under development.

Feedback/Correction: [Click here!](https://forms.gle/LehGfBWFX3yWFDBH6).
:::

::: column-screen-inset-right
| Week | Topic | Prepare | PDF |
|:------:|--------|--------|:------:|
| [1](./pages/Wk01.html) | Introduction; Unsupervised Learning - Representation learning - PCA | | [🖥️](./notes/Wk01.pdf "PDF"){aria-label="Lab 0 slides"} |
| [2](./pages/Wk02.html) | Unsupervised Learning - Representation learning - Kernel PCA | | [🖥️](./notes/Wk02.pdf "PDF"){aria-label="Lab 0 slides"} |
| [3](./pages/Wk03.html) | Unsupervised Learning - Clustering - K-means/Kernel K-means | | [🖥️](./notes/Wk03.pdf "PDF"){aria-label="Lab 0 slides"} |
| [4](./pages/Wk04.html) | Unsupervised Learning - Estimation - Recap of MLE + Bayesian estimation, Gaussian Mixture Model - EM algorithm | | [🖥️](./notes/Wk04.pdf "PDF"){aria-label="Lab 0 slides"} |
| [5](./pages/Wk05.html) | Supervised Learning - Regression - Least Squares; Bayesian view | | [🖥️](./notes/Wk05.pdf "PDF"){aria-label="Lab 0 slides"} |
| [6](./pages/Wk06.html) | Supervised Learning - Regression - Ridge/LASSO | | [🖥️](./notes/Wk06.pdf "PDF"){aria-label="Lab 0 slides"} |
| [7](./pages/Wk07.html) | Supervised Learning - Classification - K-NN, Decision tree | | [🖥️](./notes/Wk07.pdf "PDF"){aria-label="Lab 0 slides"} |
| [8](./pages/Wk08.html) | Supervised Learning - Classification - Generative Models - Naive Bayes | | [🖥️](./notes/Wk08.pdf "PDF"){aria-label="Lab 0 slides"} |
| [9](./pages/Wk09.html) | Discriminative Models - Perceptron; Logistic Regression | | [🖥️](./notes/Wk09.pdf "PDF"){aria-label="Lab 0 slides"} |
| [10](./pages/Wk10.html) | Support Vector Machines | | [🖥️](./notes/Wk10.pdf "PDF"){aria-label="Lab 0 slides"} |
:::
